apiVersion: v1
kind: Pod
metadata:
  name: demo1
spec:
  containers:
    - name: aditya
      image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: demo2
spec:
  containers:
    - name: aditya
      image: nginx